//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.GPAMembers = new HashSet<GPAMember>();
        }
    
        public string BillID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
    
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<GPAMember> GPAMembers { get; set; }
    }
}
