//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPAMember
    {
        public int GPAMemberID { get; set; }
        public string MemberID { get; set; }
        public Nullable<double> GradePointAverage { get; set; }
        public string BillID { get; set; }
        public string Presentee { get; set; }
        public Nullable<System.DateTime> LastDateUpdate { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Member Member { get; set; }
    }
}
