//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Bills = new HashSet<Bill>();
            this.GPAMembers = new HashSet<GPAMember>();
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public string MemberAvatar { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public string CMND { get; set; }
        public System.DateTime CMND_Date { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string PresenteeID { get; set; }
        public string RankID { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<GPAMember> GPAMembers { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
