//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.MemberPoints = new HashSet<MemberPoint>();
            this.Orders = new HashSet<Order>();
            this.ProductDetails = new HashSet<ProductDetail>();
            this.SalePoints = new HashSet<SalePoint>();
            this.Notifies = new HashSet<Notify>();
            this.Notifies1 = new HashSet<Notify>();
        }
    
        public string MemberID { get; set; }
        public string FullName { get; set; }
        public string Avatar { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string IDCard { get; set; }
        public string IDCard_PlaceIssue { get; set; }
        public System.DateTime IDCard_DateIssue { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string ReferralID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
    
        public virtual ICollection<MemberPoint> MemberPoints { get; set; }
        public virtual Position Position { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual ICollection<SalePoint> SalePoints { get; set; }
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<Notify> Notifies { get; set; }
        public virtual ICollection<Notify> Notifies1 { get; set; }
    }
}
