//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.SalePoints = new HashSet<SalePoint>();
        }
    
        public string OrderID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<SalePoint> SalePoints { get; set; }
    }
}
