//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BasePrices = new HashSet<BasePrice>();
            this.BillDetails = new HashSet<BillDetail>();
            this.ProductDetails = new HashSet<ProductDetail>();
            this.SalesPoints = new HashSet<SalesPoint>();
            this.SellPrices = new HashSet<SellPrice>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
    
        public virtual ICollection<BasePrice> BasePrices { get; set; }
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual ICollection<SalesPoint> SalesPoints { get; set; }
        public virtual ICollection<SellPrice> SellPrices { get; set; }
    }
}
