//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public Rank()
        {
            this.Members = new HashSet<Member>();
        }
    
        public string RankID { get; set; }
        public string RankName { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
