//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string MemberID { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<double> SalaryByLower { get; set; }
        public Nullable<double> SalaryByImmediate { get; set; }
        public Nullable<double> SalaryByManager { get; set; }
        public Nullable<double> SumSalary { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
