//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPHDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePoint
    {
        public int SalePointID { get; set; }
        public string MemberID { get; set; }
        public Nullable<double> Mark { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> SaleMonth { get; set; }
        public Nullable<int> SaleYear { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Order Order { get; set; }
    }
}
